#Minecraft server properties
#Fri Sep 05 11:43:34 GMT 2025
view-distance=4
max-build-height=256
server-ip=
level-seed=4180886088203421752
allow-nether=true
gamemode=0
enable-command-block=false
server-port=25565
enable-rcon=false
enable-query=false
op-permission-level=4
prevent-proxy-connections=false
generator-settings=
resource-pack=
player-idle-timeout=0
level-name=world
motd=A Minecraft Server
force-gamemode=true
debug=false
hardcore=false
white-list=false
broadcast-console-to-ops=true
pvp=true
spawn-npcs=true
spawn-animals=true
generate-structures=true
snooper-enabled=true
difficulty=2
network-compression-threshold=256
level-type=DEFAULT
spawn-monsters=true
max-players=20
use-native-transport=true
spawn-protection=16
resource-pack-sha1=
online-mode=false
allow-flight=false
max-world-size=29999984
